### ISSUE TITLE
Mise à niveau du thème • review

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/tactic-site#1]
- [x] Actualités passées en layout list (volontaire ou non)
- [x] Dans une organisation manque affichage du site web ([en ligne](https://tactic.14septembre.fr/fr/organisations/klepierre/) | [en local](http://localhost:1313/fr/organisations/klepierre/))
- [x] Dans la page "Qui nous sommes", pas d'affichage des avatars en mobile ([en ligne](https://tactic.14septembre.fr/fr/qui-nous-sommes/#block-4) | [en local](http://localhost:1313/fr/qui-nous-sommes/#block-4))

**Comment by arnaudlevy** [comment]
le passage en liste n'est pas volontaire, c'est la config qui est passée en yaml
